[tool.poetry]
name = "user-service-example"
version = "0.1.0"
description = "A simple user service example"
authors = ["ericsalesdeandrade <sdaeric19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.123.10"
uvicorn = "^0.41.0"
pydantic = "^2.12.5"
httpx = "^0.28.1"
sqlalchemy-utils = "^0.42.1"
PyJWT = "^2.8.0"


[tool.poetry.group.test.dependencies]
pytest = "^9.0.2"
pytest-randomly = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
